### ISSUE TITLE
Directory rename

### ISSUE THREAD

**Issue by nderjung** [unikraft/tools#2]
Since this is early on in the project,  I am opening this issue to discuss the naming conventions of current directories, I propose:

* `automatic_build_tool` -> `build`
* `dependency_analysis_tool` -> `depends`
* `utils_toolchain` -> `utils`

This may seem somewhat pedantic but it makes for neater URI on imports and follows the [Go convention](https://golang.org/doc/effective_go.html#package-names).  :)

(So far it all looks good, hoping to dig into this a bit more..)

**Comment by gaulthiergain** [comment]
Hi @nderjung, interesting remark. I will do it in next commit.
